# Generated by Django 5.2.4 on 2025-07-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_student_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('priority_level', models.CharField(max_length=50)),
                ('complaint_content', models.TextField()),
                ('complaint_answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to='accounts.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='accounts.student')),
            ],
        ),
    ]
