# Generated by Django 5.2.4 on 2025-07-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsuggs', '0002_complaint_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
