# Generated by Django 5.2.4 on 2025-07-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_password_reset_token_and_more'),
        ('compsuggs', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('suggestion_content', models.TextField()),
                ('suggestion_answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_suggestions', to='accounts.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts.student')),
            ],
        ),
    ]
