# Generated by Django 5.2.4 on 2025-08-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsuggs', '0004_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
