# Generated by Django 5.2.4 on 2025-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('national_id_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=100)),
                ('admin_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Seat_Number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Seat_Number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos_student/')),
                ('department', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
    ]
